import type { PsychologyClass } from "./schema";

export const PSYCHOLOGY_CLASSES: PsychologyClass[] = [
  {
    id: "clase-4-memoria",
    number: 4,
    title: "Memoria",
    routeSlug: "memoria",
    centralTheme:
      "La memoria como sistema de codificación, almacenamiento, recuperación y reconstrucción de información.",
    centralIdea:
      "La memoria humana no funciona como una grabación exacta: reconstruye información usando esquemas, asociaciones, claves contextuales y experiencias previas.",
    sourceRefs: [
      {
        kind: "ppt",
        label: "Clase 4 - PSI1101-2.pdf",
        detail: "Diapositivas sobre memoria constructiva, modelo modal, Baddeley, codificación, recuperación y amnesias.",
      },
      {
        kind: "texto",
        label: "Gray (2008), Capítulo 9",
        detail: "Memoria y conciencia.",
      },
      {
        kind: "cuaderno",
        label: "Procesos Psicológicos Básicos.pdf",
        detail: "Apuntes de Clase 4.",
      },
    ],
    keyConceptIds: [
      "memoria-sensorial",
      "memoria-trabajo",
      "memoria-largo-plazo",
      "modelo-modal",
      "baddeley",
      "bucle-fonologico",
      "agenda-visoespacial",
      "ejecutivo-central",
      "elaboracion",
      "claves-contextuales",
      "memoria-constructiva",
      "falsas-memorias",
      "amnesia-retrograda",
      "amnesia-anterograda",
      "memoria-explicita",
      "memoria-episodica",
      "memoria-semantica",
      "memoria-implicita",
    ],
    authorIds: ["gray", "baddeley", "bartlett", "dupuy"],
    subtopicIds: [
      "modelo-modal-memoria",
      "memoria-trabajo-baddeley",
      "codificacion-largo-plazo",
      "recuperacion",
      "distorsion-falsas-memorias",
      "amnesias",
      "memorias-multiples",
    ],
    examDisposition: {
      probability: "alta",
      likelyFormats: ["alternativa", "desarrollo", "aplicacion", "integracion"],
      expectedTraps: [
        "Confundir memoria de trabajo con memoria de largo plazo.",
        "Creer que memoria constructiva significa simplemente mala memoria.",
        "Confundir memoria episódica con memoria semántica.",
        "Confundir amnesia retrógrada con anterógrada.",
      ],
    },
  },
  {
    id: "clase-5-aprendizaje",
    number: 5,
    title: "Aprendizaje",
    routeSlug: "aprendizaje",
    centralTheme:
      "El aprendizaje como cambio relativamente permanente en el comportamiento generado por la experiencia.",
    centralIdea:
      "La conducta cambia por asociaciones entre estímulos o por consecuencias que aumentan o disminuyen respuestas.",
    sourceRefs: [
      {
        kind: "ppt",
        label: "Clase 5 - PSI1101 (2026).pdf",
        detail: "Condicionamiento clásico, condicionamiento operante y programas de reforzamiento.",
      },
      {
        kind: "texto",
        label: "Feldman, Capítulo de aprendizaje",
        detail: "Condicionamiento clásico y operante.",
      },
      {
        kind: "cuaderno",
        label: "Procesos Psicológicos Básicos.pdf",
        detail: "Apuntes de Clase 5.",
      },
    ],
    keyConceptIds: [
      "aprendizaje",
      "condicionamiento-clasico",
      "estimulo-incondicionado",
      "respuesta-incondicionada",
      "estimulo-neutro",
      "estimulo-condicionado",
      "respuesta-condicionada",
      "extincion",
      "recuperacion-espontanea",
      "generalizacion",
      "discriminacion",
      "condicionamiento-operante",
      "ley-del-efecto",
      "refuerzo-positivo",
      "refuerzo-negativo",
      "castigo-positivo",
      "castigo-negativo",
      "programas-reforzamiento",
      "razon-fija",
      "razon-variable",
      "intervalo-fijo",
      "intervalo-variable",
      "conducta-supersticiosa",
    ],
    authorIds: ["pavlov", "watson", "skinner", "thorndike", "feldman"],
    subtopicIds: [
      "definicion-aprendizaje",
      "condicionamiento-clasico",
      "little-albert",
      "condicionamiento-operante",
      "refuerzo-castigo",
      "programas-reforzamiento",
      "supersticion",
      "redes-sociales",
    ],
    examDisposition: {
      probability: "alta",
      likelyFormats: ["alternativa", "desarrollo", "aplicacion"],
      expectedTraps: [
        "Confundir refuerzo negativo con castigo.",
        "Confundir positivo/negativo con bueno/malo.",
        "Identificar mal EI, RI, EC y RC.",
        "Confundir generalización con discriminación.",
      ],
    },
  },
  {
    id: "clase-6-razonamiento-inteligencia",
    number: 6,
    title: "Razonamiento e Inteligencia",
    routeSlug: "razonamiento-inteligencia",
    centralTheme:
      "El razonamiento como uso de memoria y experiencia para comprender situaciones, anticipar consecuencias, resolver problemas y adaptarse.",
    centralIdea:
      "Las personas razonan inductiva y deductivamente, pero sus decisiones pueden verse afectadas por sesgos; la inteligencia se entiende como capacidad para razonar, resolver problemas y adquirir conocimiento.",
    sourceRefs: [
      {
        kind: "ppt",
        label: "Clase 6 - PSI1101 (2026).pdf",
        detail: "Razonamiento inductivo, deductivo, sesgos, insight e inteligencia.",
      },
      {
        kind: "texto",
        label: "Gray (2008), Capítulo 10",
        detail: "Razonamiento e inteligencia.",
      },
      {
        kind: "cuaderno",
        label: "Procesos Psicológicos Básicos.pdf",
        detail: "Apuntes de Clase 6.",
      },
    ],
    keyConceptIds: [
      "razonamiento-inductivo",
      "razonamiento-deductivo",
      "analogias",
      "sesgo-disponibilidad",
      "sesgo-confirmacion",
      "sesgo-mundo-predecible",
      "validez-logica",
      "insight",
      "problema-vela",
      "fijacion-funcional",
      "inteligencia",
      "factor-g",
      "inteligencia-fluida",
      "inteligencia-cristalizada",
      "ci",
    ],
    authorIds: [
      "gray",
      "duncker",
      "galton",
      "binet",
      "wechsler",
      "spearman",
      "cattell",
    ],
    subtopicIds: [
      "razonamiento-inductivo",
      "razonamiento-deductivo",
      "sesgos",
      "insight-creatividad",
      "pruebas-inteligencia",
      "factor-g",
      "fluida-cristalizada",
    ],
    examDisposition: {
      probability: "alta",
      likelyFormats: ["alternativa", "desarrollo", "aplicacion", "integracion"],
      expectedTraps: [
        "Confundir inducción con deducción.",
        "Evaluar la verdad del contenido en vez de la validez lógica.",
        "Confundir disponibilidad con confirmación.",
        "Confundir inteligencia fluida con cristalizada.",
      ],
    },
  },
  {
    id: "clase-7-lenguaje",
    number: 7,
    title: "Lenguaje",
    routeSlug: "lenguaje",
    centralTheme:
      "El lenguaje como medio de comunicación, pensamiento, cultura, representación y creación de realidad social.",
    centralIdea:
      "El lenguaje no solo comunica pensamientos: también influye en cómo organizamos la experiencia psicológica y cultural.",
    sourceRefs: [
      {
        kind: "ppt",
        label: "Clase 7 - PSI1101 (2026).pdf",
        detail: "Lenguaje como comunicación, pensamiento, cultura, gramática, adquisición y Sapir-Whorf.",
      },
      {
        kind: "texto",
        label: "Feldman (2010), Capítulo 7, Módulo 22",
        detail: "Lenguaje.",
      },
      {
        kind: "cuaderno",
        label: "Procesos Psicológicos Básicos.pdf",
        detail: "Apuntes de Clase 7.",
      },
    ],
    keyConceptIds: [
      "lenguaje",
      "lenguaje-comunicacion",
      "lenguaje-pensamiento",
      "lenguaje-cultura",
      "lenguaje-sistema",
      "lenguaje-uso",
      "gramatica",
      "fonologia",
      "fonema",
      "sintaxis",
      "semantica",
      "balbuceo",
      "habla-telegrafica",
      "teoria-aprendizaje-lenguaje",
      "innatismo",
      "gramatica-universal",
      "dispositivo-adquisicion-lenguaje",
      "interaccionismo",
      "broca",
      "wernicke",
      "fasciculo-arqueado",
      "relatividad-linguistica",
      "sapir-whorf",
      "hipotesis-fuerte",
      "hipotesis-debil",
      "aymara",
    ],
    authorIds: ["feldman", "chomsky", "sapir-whorf", "skinner"],
    subtopicIds: [
      "lenguaje-como-comunicacion-pensamiento",
      "lenguaje-cultura",
      "gramatica",
      "desarrollo-lenguaje",
      "teorias-adquisicion-lenguaje",
      "bases-neurales",
      "relatividad-linguistica",
    ],
    examDisposition: {
      probability: "alta",
      likelyFormats: ["alternativa", "desarrollo", "aplicacion", "integracion"],
      expectedTraps: [
        "Reducir lenguaje solo a comunicación.",
        "Confundir sintaxis con semántica.",
        "Confundir hipótesis fuerte con hipótesis débil.",
        "Presentar Sapir-Whorf solo como determinismo absoluto.",
      ],
    },
  },
];