export const MAT1000_FILTER_OPTIONS = {
  evaluaciones: ["I1", "I2", "I3", "EXAMEN"],
  modulos: [
    "Módulo 1: Recta y parábola",
    "Módulo 2: Inecuaciones",
    "Módulo 3: Funciones reales",
    "Módulo 4: Exponenciales y logaritmos",
    "Módulo 5: Trigonometría",
    "Módulo 6: Polinomios",
    "Módulo 7: Sucesiones y sumas",
  ],
  subtemas: [
    "Distancia entre puntos",
    "Intersección con ejes coordenados",
    "Ecuación de la recta",
    "Rectas paralelas y perpendiculares",
    "Sistemas lineales 2x2",
    "Parábola y modelos cuadráticos",
    "Intervalos",
    "Inecuaciones lineales",
    "Inecuaciones cuadráticas",
    "Inecuaciones racionales",
    "Valor absoluto",
    "Dominio",
    "Recorrido",
    "Composición de funciones",
    "Función inversa",
    "Funciones por tramos",
    "Ecuaciones exponenciales",
    "Ecuaciones logarítmicas",
    "Circunferencia unitaria",
    "Radianes",
    "Ángulos notables",
  ],
} as const
